# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-001001000000001'
# Mobile Country Code value
mcc: '001'
# Mobile Network Code value (2 or 3 digits)
mnc: '001'

# Permanent subscription key
key: '465b5ce8b199b49faa5f0a2ee238a001'
# Operator code (OP) of the UE. This value be either 'OP' or 'OPC'
op: 'cdc202d5123e20f62b6d676ac72cb318'
opType: 'OP'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 127.0.0.1

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1

# List of requested S-NSSAIs by this UE
slices:
  - sst: 1

# Supported encryption and integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true
ciphering:
  EA1: true
  EA2: true
  EA3: true
