gnbId: 1
tac: 117
nci: '0000000100'

host: 127.0.0.1
gtpHost: 127.0.0.1
gtpPort: 2152

plmn:
  mcc: 1
  mnc: 1

amfConfigs:
  - host: 10.154.14.19
    port: 38421

nssais:
  - sst: '0x01'

ignoreStreamIds: true
